module.exports = {
  head: {
    titleTemplate: '%s | Sentimony Records',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
    ],
    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Montserrat' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Julius+Sans+One' },
      { rel: 'shortcut icon', href: 'https://content.sentimony.com/assets/img/favicons/sentimony/favicon-32.png' },
      { rel: 'apple-touch-icon', href: 'https://content.sentimony.com/assets/img/favicons/sentimony/favicon-144.png' },
    ]
  },
  loading: {
    color: 'rgba(255,255,255,0.5)',
    height: '5px',
  },
  plugins: [
    { src: '~/plugins/google-analytics.js', ssr: false },
    { src: '~/plugins/vue-awesome-swiper.js', ssr: true },
    // { src: '~/plugins/vue-tabs.js', ssr: false },
    { src: '~/plugins/v-img.js', ssr: false },
    { src: '~/plugins/fireauth.js', ssr: false },
    { src: '~/plugins/vue-ripple-directive.js', ssr: false },
    { src: '~/plugins/vue-mq.js', ssr: true },
    { src: '~/plugins/vue-disqus', ssr: true },
  ],
  css: [
    'normalize.css/normalize.css',
    'swiper/css/swiper.css',
    'assets/scss/base.scss',
    // 'swiper/swiper-bundle.css',
    // 'vue-nav-tabs/dist/vue-tabs.min.css',
  ],
  modules: [
    'nuxt-facebook-pixel-module',
  ],
  facebook: {
    track: 'PageView',
    pixelId: 168167750758036,
    version: '2.0',
    disabled: false,
  },
  build: {
    vendor: ['axios'],
    analyze: {
      analyzerMode: 'static'
    }
  },
  router: {
    scrollBehavior: function (to, from, savedPosition) {
      return { x: 0, y: 0 }
    }
  },
  generate: {
    routes: [
      '/release/va-fantazma',
      '/release/va-fantazma/official',
      '/release/va-fantazma/bandcamp',
      '/release/va-fantazma/bandcamp24',
      '/release/va-fantazma/itunes',
      '/release/va-fantazma/beatport',
      '/release/va-fantazma/spotify',
      '/release/va-fantazma/junodownload',
      '/release/va-fantazma/youtube',
      '/release/va-fantazma/youtubemusic',
      '/release/va-fantazma/deezer',
      '/release/va-fantazma/tidal',
      '/release/va-fantazma/napster',
      '/release/va-fantazma/soundcloud',

      '/release/va-emptinesses',
      '/release/va-emptinesses/official',
      '/release/va-emptinesses/bandcamp',
      '/release/va-emptinesses/bandcamp24',
      '/release/va-emptinesses/itunes',
      '/release/va-emptinesses/beatport',
      '/release/va-emptinesses/spotify',
      '/release/va-emptinesses/junodownload',
      '/release/va-emptinesses/youtube',
      '/release/va-emptinesses/youtubemusic',
      '/release/va-emptinesses/deezer',
      '/release/va-emptinesses/tidal',
      '/release/va-emptinesses/napster',
      '/release/va-emptinesses/soundcloud',

      '/release/sphingida-origin',
      '/release/sphingida-origin/official',
      '/release/sphingida-origin/bandcamp',
      '/release/sphingida-origin/bandcamp24',
      '/release/sphingida-origin/itunes',
      '/release/sphingida-origin/beatport',
      '/release/sphingida-origin/spotify',
      '/release/sphingida-origin/junodownload',
      '/release/sphingida-origin/youtube',
      '/release/sphingida-origin/youtubemusic',
      '/release/sphingida-origin/deezer',
      '/release/sphingida-origin/tidal',
      '/release/sphingida-origin/napster',
      '/release/sphingida-origin/soundcloud',

      '/release/va-true-story',
      '/release/va-true-story/official',
      '/release/va-true-story/bandcamp',
      '/release/va-true-story/bandcamp24',
      '/release/va-true-story/itunes',
      '/release/va-true-story/beatport',
      '/release/va-true-story/spotify',
      '/release/va-true-story/junodownload',
      '/release/va-true-story/youtube',
      '/release/va-true-story/youtubemusic',
      '/release/va-true-story/deezer',
      '/release/va-true-story/tidal',
      '/release/va-true-story/napster',
      '/release/va-true-story/soundcloud',

      '/release/spectrum-vision-lost-space-device',
      '/release/spectrum-vision-lost-space-device/official',
      '/release/spectrum-vision-lost-space-device/bandcamp',
      '/release/spectrum-vision-lost-space-device/bandcamp24',
      '/release/spectrum-vision-lost-space-device/itunes',
      '/release/spectrum-vision-lost-space-device/beatport',
      '/release/spectrum-vision-lost-space-device/spotify',
      '/release/spectrum-vision-lost-space-device/junodownload',
      '/release/spectrum-vision-lost-space-device/youtube',
      '/release/spectrum-vision-lost-space-device/youtubemusic',
      '/release/spectrum-vision-lost-space-device/deezer',
      '/release/spectrum-vision-lost-space-device/tidal',
      '/release/spectrum-vision-lost-space-device/napster',
      '/release/spectrum-vision-lost-space-device/soundcloud',

      '/release/irukanji-z-lisu',
      '/release/irukanji-z-lisu/official',
      '/release/irukanji-z-lisu/bandcamp',
      '/release/irukanji-z-lisu/bandcamp24',
      '/release/irukanji-z-lisu/itunes',
      '/release/irukanji-z-lisu/beatport',
      '/release/irukanji-z-lisu/spotify',
      '/release/irukanji-z-lisu/junodownload',
      '/release/irukanji-z-lisu/youtube',
      '/release/irukanji-z-lisu/youtubemusic',
      '/release/irukanji-z-lisu/deezer',
      '/release/irukanji-z-lisu/tidal',
      '/release/irukanji-z-lisu/napster',
      '/release/irukanji-z-lisu/soundcloud',

      '/release/va-ocean-scenes-higher-titans',
      '/release/va-ocean-scenes-higher-titans/official',
      '/release/va-ocean-scenes-higher-titans/bandcamp',
      '/release/va-ocean-scenes-higher-titans/bandcamp24',
      '/release/va-ocean-scenes-higher-titans/itunes',
      '/release/va-ocean-scenes-higher-titans/beatport',
      '/release/va-ocean-scenes-higher-titans/spotify',
      '/release/va-ocean-scenes-higher-titans/junodownload',
      '/release/va-ocean-scenes-higher-titans/youtube',
      '/release/va-ocean-scenes-higher-titans/youtubemusic',
      '/release/va-ocean-scenes-higher-titans/deezer',
      '/release/va-ocean-scenes-higher-titans/tidal',
      '/release/va-ocean-scenes-higher-titans/napster',
      '/release/va-ocean-scenes-higher-titans/soundcloud',

      '/release/senzar-before-the-morning-sun',
      '/release/senzar-before-the-morning-sun/official',
      '/release/senzar-before-the-morning-sun/bandcamp',
      '/release/senzar-before-the-morning-sun/bandcamp24',
      '/release/senzar-before-the-morning-sun/itunes',
      '/release/senzar-before-the-morning-sun/beatport',
      '/release/senzar-before-the-morning-sun/spotify',
      '/release/senzar-before-the-morning-sun/junodownload',
      '/release/senzar-before-the-morning-sun/youtube',
      '/release/senzar-before-the-morning-sun/youtubemusic',
      '/release/senzar-before-the-morning-sun/deezer',
      '/release/senzar-before-the-morning-sun/tidal',
      '/release/senzar-before-the-morning-sun/napster',
      '/release/senzar-before-the-morning-sun/soundcloud',

      '/release/va-grower',
      '/release/va-grower/official',
      '/release/va-grower/bandcamp',
      '/release/va-grower/bandcamp24',
      '/release/va-grower/itunes',
      '/release/va-grower/beatport',
      '/release/va-grower/spotify',
      '/release/va-grower/junodownload',
      '/release/va-grower/youtube',
      '/release/va-grower/youtubemusic',
      '/release/va-grower/deezer',
      '/release/va-grower/tidal',
      '/release/va-grower/napster',
      '/release/va-grower/soundcloud',

      '/release/va-time-loop-beyond-borders',
      '/release/va-time-loop-beyond-borders/official',
      '/release/va-time-loop-beyond-borders/bandcamp',
      '/release/va-time-loop-beyond-borders/bandcamp24',
      '/release/va-time-loop-beyond-borders/itunes',
      '/release/va-time-loop-beyond-borders/beatport',
      '/release/va-time-loop-beyond-borders/spotify',
      '/release/va-time-loop-beyond-borders/junodownload',
      '/release/va-time-loop-beyond-borders/youtube',
      '/release/va-time-loop-beyond-borders/youtubemusic',
      '/release/va-time-loop-beyond-borders/deezer',
      '/release/va-time-loop-beyond-borders/tidal',
      '/release/va-time-loop-beyond-borders/napster',
      '/release/va-time-loop-beyond-borders/soundcloud',

      '/release/unusual-cosmic-process-weightlessness',
      '/release/unusual-cosmic-process-weightlessness/official',
      '/release/unusual-cosmic-process-weightlessness/bandcamp',
      '/release/unusual-cosmic-process-weightlessness/bandcamp24',
      '/release/unusual-cosmic-process-weightlessness/itunes',
      '/release/unusual-cosmic-process-weightlessness/beatport',
      '/release/unusual-cosmic-process-weightlessness/spotify',
      '/release/unusual-cosmic-process-weightlessness/junodownload',
      '/release/unusual-cosmic-process-weightlessness/youtube',
      '/release/unusual-cosmic-process-weightlessness/youtubemusic',
      '/release/unusual-cosmic-process-weightlessness/deezer',
      '/release/unusual-cosmic-process-weightlessness/tidal',
      '/release/unusual-cosmic-process-weightlessness/napster',
      '/release/unusual-cosmic-process-weightlessness/soundcloud',

      '/release/va-tempo-syndicate',
      '/release/va-tempo-syndicate/official',
      '/release/va-tempo-syndicate/bandcamp',
      '/release/va-tempo-syndicate/bandcamp24',
      '/release/va-tempo-syndicate/itunes',
      '/release/va-tempo-syndicate/beatport',
      '/release/va-tempo-syndicate/spotify',
      '/release/va-tempo-syndicate/junodownload',
      '/release/va-tempo-syndicate/youtube',
      '/release/va-tempo-syndicate/youtubemusic',
      '/release/va-tempo-syndicate/deezer',
      '/release/va-tempo-syndicate/tidal',
      '/release/va-tempo-syndicate/napster',
      '/release/va-tempo-syndicate/soundcloud',

      '/release/va-dancing-mavka',
      '/release/va-dancing-mavka/official',
      '/release/va-dancing-mavka/bandcamp',
      '/release/va-dancing-mavka/bandcamp24',
      '/release/va-dancing-mavka/itunes',
      '/release/va-dancing-mavka/beatport',
      '/release/va-dancing-mavka/spotify',
      '/release/va-dancing-mavka/junodownload',
      '/release/va-dancing-mavka/youtube',
      '/release/va-dancing-mavka/youtubemusic',
      '/release/va-dancing-mavka/deezer',
      '/release/va-dancing-mavka/tidal',
      '/release/va-dancing-mavka/napster',
      '/release/va-dancing-mavka/soundcloud',

      '/release/va-absence-of-gravity',
      '/release/va-absence-of-gravity/official',
      '/release/va-absence-of-gravity/bandcamp',
      '/release/va-absence-of-gravity/bandcamp24',
      '/release/va-absence-of-gravity/itunes',
      '/release/va-absence-of-gravity/beatport',
      '/release/va-absence-of-gravity/spotify',
      '/release/va-absence-of-gravity/junodownload',
      '/release/va-absence-of-gravity/youtube',
      '/release/va-absence-of-gravity/youtubemusic',
      '/release/va-absence-of-gravity/deezer',
      '/release/va-absence-of-gravity/tidal',
      '/release/va-absence-of-gravity/napster',
      '/release/va-absence-of-gravity/soundcloud',

      '/release/va-special-places',
      '/release/va-special-places/official',
      '/release/va-special-places/bandcamp',
      '/release/va-special-places/bandcamp24',
      '/release/va-special-places/itunes',
      '/release/va-special-places/beatport',
      '/release/va-special-places/spotify',
      '/release/va-special-places/junodownload',
      '/release/va-special-places/youtube',
      '/release/va-special-places/youtubemusic',
      '/release/va-special-places/deezer',
      '/release/va-special-places/tidal',
      '/release/va-special-places/napster',
      '/release/va-special-places/soundcloud',

      '/release/hypnotriod-seven-heavenly-edges',
      '/release/hypnotriod-seven-heavenly-edges/official',
      '/release/hypnotriod-seven-heavenly-edges/bandcamp',
      '/release/hypnotriod-seven-heavenly-edges/bandcamp24',
      '/release/hypnotriod-seven-heavenly-edges/itunes',
      '/release/hypnotriod-seven-heavenly-edges/beatport',
      '/release/hypnotriod-seven-heavenly-edges/spotify',
      '/release/hypnotriod-seven-heavenly-edges/junodownload',
      '/release/hypnotriod-seven-heavenly-edges/youtube',
      '/release/hypnotriod-seven-heavenly-edges/youtubemusic',
      '/release/hypnotriod-seven-heavenly-edges/deezer',
      '/release/hypnotriod-seven-heavenly-edges/tidal',
      '/release/hypnotriod-seven-heavenly-edges/napster',
      '/release/hypnotriod-seven-heavenly-edges/soundcloud',

      '/release/specialmind-the-missing-particle',
      '/release/specialmind-the-missing-particle/official',
      '/release/specialmind-the-missing-particle/bandcamp',
      '/release/specialmind-the-missing-particle/bandcamp24',
      '/release/specialmind-the-missing-particle/itunes',
      '/release/specialmind-the-missing-particle/beatport',
      '/release/specialmind-the-missing-particle/spotify',
      '/release/specialmind-the-missing-particle/junodownload',
      '/release/specialmind-the-missing-particle/youtube',
      '/release/specialmind-the-missing-particle/youtubemusic',
      '/release/specialmind-the-missing-particle/deezer',
      '/release/specialmind-the-missing-particle/tidal',
      '/release/specialmind-the-missing-particle/napster',
      '/release/specialmind-the-missing-particle/soundcloud',

      '/release/tentura-aurora',
      '/release/tentura-aurora/official',
      '/release/tentura-aurora/bandcamp',
      '/release/tentura-aurora/bandcamp24',
      '/release/tentura-aurora/itunes',
      '/release/tentura-aurora/beatport',
      '/release/tentura-aurora/spotify',
      '/release/tentura-aurora/junodownload',
      '/release/tentura-aurora/youtube',
      '/release/tentura-aurora/youtubemusic',
      '/release/tentura-aurora/deezer',
      '/release/tentura-aurora/tidal',
      '/release/tentura-aurora/napster',
      '/release/tentura-aurora/soundcloud',

      '/release/cifroteca-roof-raiser-wild-storm',
      '/release/cifroteca-roof-raiser-wild-storm/official',
      '/release/cifroteca-roof-raiser-wild-storm/bandcamp',
      '/release/cifroteca-roof-raiser-wild-storm/bandcamp24',
      '/release/cifroteca-roof-raiser-wild-storm/itunes',
      '/release/cifroteca-roof-raiser-wild-storm/beatport',
      '/release/cifroteca-roof-raiser-wild-storm/spotify',
      '/release/cifroteca-roof-raiser-wild-storm/junodownload',
      '/release/cifroteca-roof-raiser-wild-storm/youtube',
      '/release/cifroteca-roof-raiser-wild-storm/youtubemusic',
      '/release/cifroteca-roof-raiser-wild-storm/deezer',
      '/release/cifroteca-roof-raiser-wild-storm/tidal',
      '/release/cifroteca-roof-raiser-wild-storm/napster',
      '/release/cifroteca-roof-raiser-wild-storm/soundcloud',

      '/release/va-gamayun-tale',
      '/release/va-gamayun-tale/official',
      '/release/va-gamayun-tale/bandcamp',
      '/release/va-gamayun-tale/bandcamp24',
      '/release/va-gamayun-tale/itunes',
      '/release/va-gamayun-tale/beatport',
      '/release/va-gamayun-tale/spotify',
      '/release/va-gamayun-tale/junodownload',
      '/release/va-gamayun-tale/youtube',
      '/release/va-gamayun-tale/youtubemusic',
      '/release/va-gamayun-tale/deezer',
      '/release/va-gamayun-tale/tidal',
      '/release/va-gamayun-tale/napster',
      '/release/va-gamayun-tale/soundcloud',

      '/release/psyfactor-retro-scientific',
      '/release/psyfactor-retro-scientific/official',
      '/release/psyfactor-retro-scientific/bandcamp',
      '/release/psyfactor-retro-scientific/bandcamp24',
      '/release/psyfactor-retro-scientific/itunes',
      '/release/psyfactor-retro-scientific/beatport',
      '/release/psyfactor-retro-scientific/spotify',
      '/release/psyfactor-retro-scientific/junodownload',
      '/release/psyfactor-retro-scientific/youtube',
      '/release/psyfactor-retro-scientific/youtubemusic',
      '/release/psyfactor-retro-scientific/deezer',
      '/release/psyfactor-retro-scientific/tidal',
      '/release/psyfactor-retro-scientific/napster',
      '/release/psyfactor-retro-scientific/soundcloud',

      '/release/ufomatka-the-ep',
      '/release/ufomatka-the-ep/official',
      '/release/ufomatka-the-ep/bandcamp',
      '/release/ufomatka-the-ep/bandcamp24',
      '/release/ufomatka-the-ep/itunes',
      '/release/ufomatka-the-ep/beatport',
      '/release/ufomatka-the-ep/spotify',
      '/release/ufomatka-the-ep/junodownload',
      '/release/ufomatka-the-ep/youtube',
      '/release/ufomatka-the-ep/youtubemusic',
      '/release/ufomatka-the-ep/deezer',
      '/release/ufomatka-the-ep/tidal',
      '/release/ufomatka-the-ep/napster',
      '/release/ufomatka-the-ep/soundcloud',

      '/release/tentura-beyond-illusion',
      '/release/tentura-beyond-illusion/official',
      '/release/tentura-beyond-illusion/bandcamp',
      '/release/tentura-beyond-illusion/bandcamp24',
      '/release/tentura-beyond-illusion/itunes',
      '/release/tentura-beyond-illusion/beatport',
      '/release/tentura-beyond-illusion/spotify',
      '/release/tentura-beyond-illusion/junodownload',
      '/release/tentura-beyond-illusion/youtube',
      '/release/tentura-beyond-illusion/youtubemusic',
      '/release/tentura-beyond-illusion/deezer',
      '/release/tentura-beyond-illusion/tidal',
      '/release/tentura-beyond-illusion/napster',
      '/release/tentura-beyond-illusion/soundcloud',

      '/release/va-the-ten',
      '/release/va-the-ten/official',
      '/release/va-the-ten/bandcamp',
      '/release/va-the-ten/bandcamp24',
      '/release/va-the-ten/itunes',
      '/release/va-the-ten/beatport',
      '/release/va-the-ten/spotify',
      '/release/va-the-ten/junodownload',
      '/release/va-the-ten/youtube',
      '/release/va-the-ten/youtubemusic',
      '/release/va-the-ten/deezer',
      '/release/va-the-ten/tidal',
      '/release/va-the-ten/napster',
      '/release/va-the-ten/soundcloud',

      '/release/zymosis-insight',
      '/release/zymosis-insight/official',
      '/release/zymosis-insight/bandcamp',
      '/release/zymosis-insight/bandcamp24',
      '/release/zymosis-insight/itunes',
      '/release/zymosis-insight/beatport',
      '/release/zymosis-insight/spotify',
      '/release/zymosis-insight/junodownload',
      '/release/zymosis-insight/youtube',
      '/release/zymosis-insight/youtubemusic',
      '/release/zymosis-insight/deezer',
      '/release/zymosis-insight/tidal',
      '/release/zymosis-insight/napster',
      '/release/zymosis-insight/soundcloud',

      '/release/overdream-beautiful-thinking',
      '/release/overdream-beautiful-thinking/official',
      '/release/overdream-beautiful-thinking/bandcamp',
      '/release/overdream-beautiful-thinking/bandcamp24',
      '/release/overdream-beautiful-thinking/itunes',
      '/release/overdream-beautiful-thinking/beatport',
      '/release/overdream-beautiful-thinking/spotify',
      '/release/overdream-beautiful-thinking/junodownload',
      '/release/overdream-beautiful-thinking/youtube',
      '/release/overdream-beautiful-thinking/youtubemusic',
      '/release/overdream-beautiful-thinking/deezer',
      '/release/overdream-beautiful-thinking/tidal',
      '/release/overdream-beautiful-thinking/napster',
      '/release/overdream-beautiful-thinking/soundcloud',

      '/release/ufomatka-altering-the-synaptic-controllers',
      '/release/ufomatka-altering-the-synaptic-controllers/official',
      '/release/ufomatka-altering-the-synaptic-controllers/bandcamp',
      '/release/ufomatka-altering-the-synaptic-controllers/bandcamp24',
      '/release/ufomatka-altering-the-synaptic-controllers/itunes',
      '/release/ufomatka-altering-the-synaptic-controllers/beatport',
      '/release/ufomatka-altering-the-synaptic-controllers/spotify',
      '/release/ufomatka-altering-the-synaptic-controllers/junodownload',
      '/release/ufomatka-altering-the-synaptic-controllers/youtube',
      '/release/ufomatka-altering-the-synaptic-controllers/youtubemusic',
      '/release/ufomatka-altering-the-synaptic-controllers/deezer',
      '/release/ufomatka-altering-the-synaptic-controllers/tidal',
      '/release/ufomatka-altering-the-synaptic-controllers/napster',
      '/release/ufomatka-altering-the-synaptic-controllers/soundcloud',

      '/release/omnisound-destiny',
      '/release/omnisound-destiny/official',
      '/release/omnisound-destiny/bandcamp',
      '/release/omnisound-destiny/bandcamp24',
      '/release/omnisound-destiny/itunes',
      '/release/omnisound-destiny/beatport',
      '/release/omnisound-destiny/spotify',
      '/release/omnisound-destiny/junodownload',
      '/release/omnisound-destiny/youtube',
      '/release/omnisound-destiny/youtubemusic',
      '/release/omnisound-destiny/deezer',
      '/release/omnisound-destiny/tidal',
      '/release/omnisound-destiny/napster',
      '/release/omnisound-destiny/soundcloud',

      '/release/zymosis-nichna',
      '/release/zymosis-nichna/official',
      '/release/zymosis-nichna/bandcamp',
      '/release/zymosis-nichna/bandcamp24',
      '/release/zymosis-nichna/itunes',
      '/release/zymosis-nichna/beatport',
      '/release/zymosis-nichna/spotify',
      '/release/zymosis-nichna/junodownload',
      '/release/zymosis-nichna/youtube',
      '/release/zymosis-nichna/youtubemusic',
      '/release/zymosis-nichna/deezer',
      '/release/zymosis-nichna/tidal',
      '/release/zymosis-nichna/napster',
      '/release/zymosis-nichna/soundcloud',

      '/release/va-futured-vol-1',
      '/release/va-futured-vol-1/official',
      '/release/va-futured-vol-1/bandcamp',
      '/release/va-futured-vol-1/bandcamp24',
      '/release/va-futured-vol-1/itunes',
      '/release/va-futured-vol-1/beatport',
      '/release/va-futured-vol-1/spotify',
      '/release/va-futured-vol-1/junodownload',
      '/release/va-futured-vol-1/youtube',
      '/release/va-futured-vol-1/youtubemusic',
      '/release/va-futured-vol-1/deezer',
      '/release/va-futured-vol-1/tidal',
      '/release/va-futured-vol-1/napster',
      '/release/va-futured-vol-1/soundcloud',

      '/release/psydewise-synaptic-elastic',
      '/release/psydewise-synaptic-elastic/official',
      '/release/psydewise-synaptic-elastic/bandcamp',
      '/release/psydewise-synaptic-elastic/bandcamp24',
      '/release/psydewise-synaptic-elastic/itunes',
      '/release/psydewise-synaptic-elastic/beatport',
      '/release/psydewise-synaptic-elastic/spotify',
      '/release/psydewise-synaptic-elastic/junodownload',
      '/release/psydewise-synaptic-elastic/youtube',
      '/release/psydewise-synaptic-elastic/youtubemusic',
      '/release/psydewise-synaptic-elastic/deezer',
      '/release/psydewise-synaptic-elastic/tidal',
      '/release/psydewise-synaptic-elastic/napster',
      '/release/psydewise-synaptic-elastic/soundcloud',

      '/release/u-wave-autumn-discovery',
      '/release/u-wave-autumn-discovery/official',
      '/release/u-wave-autumn-discovery/bandcamp',
      '/release/u-wave-autumn-discovery/bandcamp24',
      '/release/u-wave-autumn-discovery/itunes',
      '/release/u-wave-autumn-discovery/beatport',
      '/release/u-wave-autumn-discovery/spotify',
      '/release/u-wave-autumn-discovery/junodownload',
      '/release/u-wave-autumn-discovery/youtube',
      '/release/u-wave-autumn-discovery/youtubemusic',
      '/release/u-wave-autumn-discovery/deezer',
      '/release/u-wave-autumn-discovery/tidal',
      '/release/u-wave-autumn-discovery/napster',
      '/release/u-wave-autumn-discovery/soundcloud',

      '/release/va-futured-vol-2',
      '/release/va-futured-vol-2/official',
      '/release/va-futured-vol-2/bandcamp',
      '/release/va-futured-vol-2/bandcamp24',
      '/release/va-futured-vol-2/itunes',
      '/release/va-futured-vol-2/beatport',
      '/release/va-futured-vol-2/spotify',
      '/release/va-futured-vol-2/junodownload',
      '/release/va-futured-vol-2/youtube',
      '/release/va-futured-vol-2/youtubemusic',
      '/release/va-futured-vol-2/deezer',
      '/release/va-futured-vol-2/tidal',
      '/release/va-futured-vol-2/napster',
      '/release/va-futured-vol-2/soundcloud',

      '/release/aesthesia-perception',
      '/release/aesthesia-perception/official',
      '/release/aesthesia-perception/bandcamp',
      '/release/aesthesia-perception/bandcamp24',
      '/release/aesthesia-perception/itunes',
      '/release/aesthesia-perception/beatport',
      '/release/aesthesia-perception/spotify',
      '/release/aesthesia-perception/junodownload',
      '/release/aesthesia-perception/youtube',
      '/release/aesthesia-perception/youtubemusic',
      '/release/aesthesia-perception/deezer',
      '/release/aesthesia-perception/tidal',
      '/release/aesthesia-perception/napster',
      '/release/aesthesia-perception/soundcloud',

      '/release/juelz-dependence',
      '/release/juelz-dependence/official',
      '/release/juelz-dependence/bandcamp',
      '/release/juelz-dependence/bandcamp24',
      '/release/juelz-dependence/itunes',
      '/release/juelz-dependence/beatport',
      '/release/juelz-dependence/spotify',
      '/release/juelz-dependence/junodownload',
      '/release/juelz-dependence/youtube',
      '/release/juelz-dependence/youtubemusic',
      '/release/juelz-dependence/deezer',
      '/release/juelz-dependence/tidal',
      '/release/juelz-dependence/napster',
      '/release/juelz-dependence/soundcloud',

      '/release/unusual-cosmic-process-brain-channel',
      '/release/unusual-cosmic-process-brain-channel/official',
      '/release/unusual-cosmic-process-brain-channel/bandcamp',
      '/release/unusual-cosmic-process-brain-channel/bandcamp24',
      '/release/unusual-cosmic-process-brain-channel/itunes',
      '/release/unusual-cosmic-process-brain-channel/beatport',
      '/release/unusual-cosmic-process-brain-channel/spotify',
      '/release/unusual-cosmic-process-brain-channel/junodownload',
      '/release/unusual-cosmic-process-brain-channel/youtube',
      '/release/unusual-cosmic-process-brain-channel/youtubemusic',
      '/release/unusual-cosmic-process-brain-channel/deezer',
      '/release/unusual-cosmic-process-brain-channel/tidal',
      '/release/unusual-cosmic-process-brain-channel/napster',
      '/release/unusual-cosmic-process-brain-channel/soundcloud',

      '/release/space-organ-deep-impressions',
      '/release/space-organ-deep-impressions/official',
      '/release/space-organ-deep-impressions/bandcamp',
      '/release/space-organ-deep-impressions/bandcamp24',
      '/release/space-organ-deep-impressions/itunes',
      '/release/space-organ-deep-impressions/beatport',
      '/release/space-organ-deep-impressions/spotify',
      '/release/space-organ-deep-impressions/junodownload',
      '/release/space-organ-deep-impressions/youtube',
      '/release/space-organ-deep-impressions/youtubemusic',
      '/release/space-organ-deep-impressions/deezer',
      '/release/space-organ-deep-impressions/tidal',
      '/release/space-organ-deep-impressions/napster',
      '/release/space-organ-deep-impressions/soundcloud',

      '/release/psydewise-radio-dystopia',
      '/release/psydewise-radio-dystopia/official',
      '/release/psydewise-radio-dystopia/bandcamp',
      '/release/psydewise-radio-dystopia/bandcamp24',
      '/release/psydewise-radio-dystopia/itunes',
      '/release/psydewise-radio-dystopia/beatport',
      '/release/psydewise-radio-dystopia/spotify',
      '/release/psydewise-radio-dystopia/junodownload',
      '/release/psydewise-radio-dystopia/youtube',
      '/release/psydewise-radio-dystopia/youtubemusic',
      '/release/psydewise-radio-dystopia/deezer',
      '/release/psydewise-radio-dystopia/tidal',
      '/release/psydewise-radio-dystopia/napster',
      '/release/psydewise-radio-dystopia/soundcloud',

      '/release/artech-stringer-mode',
      '/release/artech-stringer-mode/official',
      '/release/artech-stringer-mode/bandcamp',
      '/release/artech-stringer-mode/bandcamp24',
      '/release/artech-stringer-mode/itunes',
      '/release/artech-stringer-mode/beatport',
      '/release/artech-stringer-mode/spotify',
      '/release/artech-stringer-mode/junodownload',
      '/release/artech-stringer-mode/youtube',
      '/release/artech-stringer-mode/youtubemusic',
      '/release/artech-stringer-mode/deezer',
      '/release/artech-stringer-mode/tidal',
      '/release/artech-stringer-mode/napster',
      '/release/artech-stringer-mode/soundcloud',

      '/release/va-futured-vol-3',
      '/release/va-futured-vol-3/official',
      '/release/va-futured-vol-3/bandcamp',
      '/release/va-futured-vol-3/bandcamp24',
      '/release/va-futured-vol-3/itunes',
      '/release/va-futured-vol-3/beatport',
      '/release/va-futured-vol-3/spotify',
      '/release/va-futured-vol-3/junodownload',
      '/release/va-futured-vol-3/youtube',
      '/release/va-futured-vol-3/youtubemusic',
      '/release/va-futured-vol-3/deezer',
      '/release/va-futured-vol-3/tidal',
      '/release/va-futured-vol-3/napster',
      '/release/va-futured-vol-3/soundcloud',

      '/release/va-gatekey-vol-1',
      '/release/va-gatekey-vol-1/official',
      '/release/va-gatekey-vol-1/bandcamp',
      '/release/va-gatekey-vol-1/bandcamp24',
      '/release/va-gatekey-vol-1/itunes',
      '/release/va-gatekey-vol-1/beatport',
      '/release/va-gatekey-vol-1/spotify',
      '/release/va-gatekey-vol-1/junodownload',
      '/release/va-gatekey-vol-1/youtube',
      '/release/va-gatekey-vol-1/youtubemusic',
      '/release/va-gatekey-vol-1/deezer',
      '/release/va-gatekey-vol-1/tidal',
      '/release/va-gatekey-vol-1/napster',
      '/release/va-gatekey-vol-1/soundcloud',

      '/release/gojja-amber-current',
      '/release/gojja-amber-current/official',
      '/release/gojja-amber-current/bandcamp',
      '/release/gojja-amber-current/bandcamp24',
      '/release/gojja-amber-current/itunes',
      '/release/gojja-amber-current/beatport',
      '/release/gojja-amber-current/spotify',
      '/release/gojja-amber-current/junodownload',
      '/release/gojja-amber-current/youtube',
      '/release/gojja-amber-current/youtubemusic',
      '/release/gojja-amber-current/deezer',
      '/release/gojja-amber-current/tidal',
      '/release/gojja-amber-current/napster',
      '/release/gojja-amber-current/soundcloud',

      '/release/gaz-mask-quetzalcoatl',
      '/release/gaz-mask-quetzalcoatl/official',
      '/release/gaz-mask-quetzalcoatl/bandcamp',
      '/release/gaz-mask-quetzalcoatl/bandcamp24',
      '/release/gaz-mask-quetzalcoatl/itunes',
      '/release/gaz-mask-quetzalcoatl/beatport',
      '/release/gaz-mask-quetzalcoatl/spotify',
      '/release/gaz-mask-quetzalcoatl/junodownload',
      '/release/gaz-mask-quetzalcoatl/youtube',
      '/release/gaz-mask-quetzalcoatl/youtubemusic',
      '/release/gaz-mask-quetzalcoatl/deezer',
      '/release/gaz-mask-quetzalcoatl/tidal',
      '/release/gaz-mask-quetzalcoatl/napster',
      '/release/gaz-mask-quetzalcoatl/soundcloud',

      '/release/boketto-yugen',
      '/release/boketto-yugen/official',
      '/release/boketto-yugen/bandcamp',
      '/release/boketto-yugen/bandcamp24',
      '/release/boketto-yugen/itunes',
      '/release/boketto-yugen/beatport',
      '/release/boketto-yugen/spotify',
      '/release/boketto-yugen/junodownload',
      '/release/boketto-yugen/youtube',
      '/release/boketto-yugen/youtubemusic',
      '/release/boketto-yugen/deezer',
      '/release/boketto-yugen/tidal',
      '/release/boketto-yugen/napster',
      '/release/boketto-yugen/soundcloud',

      '/release/kabi-mboko',
      '/release/kabi-mboko/official',
      '/release/kabi-mboko/bandcamp',
      '/release/kabi-mboko/bandcamp24',
      '/release/kabi-mboko/itunes',
      '/release/kabi-mboko/beatport',
      '/release/kabi-mboko/spotify',
      '/release/kabi-mboko/junodownload',
      '/release/kabi-mboko/youtube',
      '/release/kabi-mboko/youtubemusic',
      '/release/kabi-mboko/deezer',
      '/release/kabi-mboko/tidal',
      '/release/kabi-mboko/napster',
      '/release/kabi-mboko/soundcloud',

      '/release/boketto-outer',
      '/release/boketto-outer/official',
      '/release/boketto-outer/bandcamp',
      '/release/boketto-outer/bandcamp24',
      '/release/boketto-outer/itunes',
      '/release/boketto-outer/beatport',
      '/release/boketto-outer/spotify',
      '/release/boketto-outer/junodownload',
      '/release/boketto-outer/youtube',
      '/release/boketto-outer/youtubemusic',
      '/release/boketto-outer/deezer',
      '/release/boketto-outer/tidal',
      '/release/boketto-outer/napster',
      '/release/boketto-outer/soundcloud',

      '/release/zymosis-timeless',
      '/release/zymosis-timeless/official',
      '/release/zymosis-timeless/bandcamp',
      '/release/zymosis-timeless/bandcamp24',
      '/release/zymosis-timeless/itunes',
      '/release/zymosis-timeless/beatport',
      '/release/zymosis-timeless/spotify',
      '/release/zymosis-timeless/junodownload',
      '/release/zymosis-timeless/youtube',
      '/release/zymosis-timeless/youtubemusic',
      '/release/zymosis-timeless/deezer',
      '/release/zymosis-timeless/tidal',
      '/release/zymosis-timeless/napster',
      '/release/zymosis-timeless/soundcloud',

      '/release/va-futured-vol-4',
      '/release/va-futured-vol-4/official',
      '/release/va-futured-vol-4/bandcamp',
      '/release/va-futured-vol-4/bandcamp24',
      '/release/va-futured-vol-4/itunes',
      '/release/va-futured-vol-4/beatport',
      '/release/va-futured-vol-4/spotify',
      '/release/va-futured-vol-4/junodownload',
      '/release/va-futured-vol-4/youtube',
      '/release/va-futured-vol-4/youtubemusic',
      '/release/va-futured-vol-4/deezer',
      '/release/va-futured-vol-4/tidal',
      '/release/va-futured-vol-4/napster',
      '/release/va-futured-vol-4/soundcloud',

      '/release/exolt-noise-no-sleep',
      '/release/exolt-noise-no-sleep/official',
      '/release/exolt-noise-no-sleep/bandcamp',
      '/release/exolt-noise-no-sleep/bandcamp24',
      '/release/exolt-noise-no-sleep/itunes',
      '/release/exolt-noise-no-sleep/beatport',
      '/release/exolt-noise-no-sleep/spotify',
      '/release/exolt-noise-no-sleep/junodownload',
      '/release/exolt-noise-no-sleep/youtube',
      '/release/exolt-noise-no-sleep/youtubemusic',
      '/release/exolt-noise-no-sleep/deezer',
      '/release/exolt-noise-no-sleep/tidal',
      '/release/exolt-noise-no-sleep/napster',
      '/release/exolt-noise-no-sleep/soundcloud',

      '/release/boketto-presence',
      '/release/boketto-presence/official',
      '/release/boketto-presence/bandcamp',
      '/release/boketto-presence/bandcamp24',
      '/release/boketto-presence/itunes',
      '/release/boketto-presence/beatport',
      '/release/boketto-presence/spotify',
      '/release/boketto-presence/junodownload',
      '/release/boketto-presence/youtube',
      '/release/boketto-presence/youtubemusic',
      '/release/boketto-presence/deezer',
      '/release/boketto-presence/tidal',
      '/release/boketto-presence/napster',
      '/release/boketto-presence/soundcloud',

      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/official',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/bandcamp',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/bandcamp24',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/itunes',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/beatport',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/spotify',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/junodownload',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/youtube',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/youtubemusic',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/deezer',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/tidal',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/napster',
      '/release/paracozm-vorg-too-weird-to-live-too-rare-to-die/soundcloud',

      '/release/psypheric-pa-leting-etter',
      '/release/psypheric-pa-leting-etter/official',
      '/release/psypheric-pa-leting-etter/bandcamp',
      '/release/psypheric-pa-leting-etter/bandcamp24',
      '/release/psypheric-pa-leting-etter/itunes',
      '/release/psypheric-pa-leting-etter/beatport',
      '/release/psypheric-pa-leting-etter/spotify',
      '/release/psypheric-pa-leting-etter/junodownload',
      '/release/psypheric-pa-leting-etter/youtube',
      '/release/psypheric-pa-leting-etter/youtubemusic',
      '/release/psypheric-pa-leting-etter/deezer',
      '/release/psypheric-pa-leting-etter/tidal',
      '/release/psypheric-pa-leting-etter/napster',
      '/release/psypheric-pa-leting-etter/soundcloud',

      '/release/boketto-immure',
      '/release/boketto-immure/official',
      '/release/boketto-immure/bandcamp',
      '/release/boketto-immure/bandcamp24',
      '/release/boketto-immure/itunes',
      '/release/boketto-immure/beatport',
      '/release/boketto-immure/spotify',
      '/release/boketto-immure/junodownload',
      '/release/boketto-immure/youtube',
      '/release/boketto-immure/youtubemusic',
      '/release/boketto-immure/deezer',
      '/release/boketto-immure/tidal',
      '/release/boketto-immure/napster',
      '/release/boketto-immure/soundcloud',

      '/release/va-gatekey-vol-2',
      '/release/va-gatekey-vol-2/official',
      '/release/va-gatekey-vol-2/bandcamp',
      '/release/va-gatekey-vol-2/bandcamp24',
      '/release/va-gatekey-vol-2/itunes',
      '/release/va-gatekey-vol-2/beatport',
      '/release/va-gatekey-vol-2/spotify',
      '/release/va-gatekey-vol-2/junodownload',
      '/release/va-gatekey-vol-2/youtube',
      '/release/va-gatekey-vol-2/youtubemusic',
      '/release/va-gatekey-vol-2/deezer',
      '/release/va-gatekey-vol-2/tidal',
      '/release/va-gatekey-vol-2/napster',
      '/release/va-gatekey-vol-2/soundcloud',
      '/release/va-gatekey-vol-2/soundclouddemo',

      '/release/space-organ-behind-the-universe',
      '/release/space-organ-behind-the-universe/official',
      '/release/space-organ-behind-the-universe/bandcamp',
      '/release/space-organ-behind-the-universe/bandcamp24',
      '/release/space-organ-behind-the-universe/itunes',
      '/release/space-organ-behind-the-universe/beatport',
      '/release/space-organ-behind-the-universe/spotify',
      '/release/space-organ-behind-the-universe/junodownload',
      '/release/space-organ-behind-the-universe/youtube',
      '/release/space-organ-behind-the-universe/youtubemusic',
      '/release/space-organ-behind-the-universe/deezer',
      '/release/space-organ-behind-the-universe/tidal',
      '/release/space-organ-behind-the-universe/napster',
      '/release/space-organ-behind-the-universe/soundcloud',
      '/release/space-organ-behind-the-universe/soundclouddemo',

      '/release/derotonin-motion-trickness',
      '/release/derotonin-motion-trickness/official',
      '/release/derotonin-motion-trickness/bandcamp',
      '/release/derotonin-motion-trickness/bandcamp24',
      '/release/derotonin-motion-trickness/itunes',
      '/release/derotonin-motion-trickness/beatport',
      '/release/derotonin-motion-trickness/spotify',
      '/release/derotonin-motion-trickness/junodownload',
      '/release/derotonin-motion-trickness/youtube',
      '/release/derotonin-motion-trickness/youtubemusic',
      '/release/derotonin-motion-trickness/deezer',
      '/release/derotonin-motion-trickness/tidal',
      '/release/derotonin-motion-trickness/napster',
      '/release/derotonin-motion-trickness/soundcloud',
      '/release/derotonin-motion-trickness/soundclouddemo',

      '/release/unusual-cosmic-process-outlines',
      '/release/unusual-cosmic-process-outlines/official',
      '/release/unusual-cosmic-process-outlines/bandcamp',
      '/release/unusual-cosmic-process-outlines/bandcamp24',
      '/release/unusual-cosmic-process-outlines/itunes',
      '/release/unusual-cosmic-process-outlines/beatport',
      '/release/unusual-cosmic-process-outlines/spotify',
      '/release/unusual-cosmic-process-outlines/junodownload',
      '/release/unusual-cosmic-process-outlines/youtube',
      '/release/unusual-cosmic-process-outlines/youtubemusic',
      '/release/unusual-cosmic-process-outlines/deezer',
      '/release/unusual-cosmic-process-outlines/tidal',
      '/release/unusual-cosmic-process-outlines/napster',
      '/release/unusual-cosmic-process-outlines/soundcloud',
      '/release/unusual-cosmic-process-outlines/soundclouddemo',

      '/release/gaz-mask-trippy-valley',
      '/release/gaz-mask-trippy-valley/official',
      '/release/gaz-mask-trippy-valley/bandcamp',
      '/release/gaz-mask-trippy-valley/bandcamp24',
      '/release/gaz-mask-trippy-valley/itunes',
      '/release/gaz-mask-trippy-valley/beatport',
      '/release/gaz-mask-trippy-valley/spotify',
      '/release/gaz-mask-trippy-valley/junodownload',
      '/release/gaz-mask-trippy-valley/youtube',
      '/release/gaz-mask-trippy-valley/youtubemusic',
      '/release/gaz-mask-trippy-valley/deezer',
      '/release/gaz-mask-trippy-valley/tidal',
      '/release/gaz-mask-trippy-valley/napster',
      '/release/gaz-mask-trippy-valley/soundcloud',
      '/release/gaz-mask-trippy-valley/soundclouddemo',

      '/release/irukanji-rebuild',
      '/release/irukanji-rebuild/official',
      '/release/irukanji-rebuild/bandcamp',
      '/release/irukanji-rebuild/bandcamp24',
      '/release/irukanji-rebuild/itunes',
      '/release/irukanji-rebuild/beatport',
      '/release/irukanji-rebuild/spotify',
      '/release/irukanji-rebuild/junodownload',
      '/release/irukanji-rebuild/youtube',
      '/release/irukanji-rebuild/youtubemusic',
      '/release/irukanji-rebuild/deezer',
      '/release/irukanji-rebuild/tidal',
      '/release/irukanji-rebuild/napster',
      '/release/irukanji-rebuild/soundcloud',

      '/release/vorg-echoes',
      '/release/vorg-echoes/official',
      '/release/vorg-echoes/bandcamp',
      '/release/vorg-echoes/bandcamp24',
      '/release/vorg-echoes/itunes',
      '/release/vorg-echoes/beatport',
      '/release/vorg-echoes/spotify',
      '/release/vorg-echoes/junodownload',
      '/release/vorg-echoes/youtube',
      '/release/vorg-echoes/youtubemusic',
      '/release/vorg-echoes/deezer',
      '/release/vorg-echoes/tidal',
      '/release/vorg-echoes/napster',
      '/release/vorg-echoes/soundcloud',

      '/release/tystix-etherial-lense',
      '/release/tystix-etherial-lense/official',
      '/release/tystix-etherial-lense/bandcamp',
      '/release/tystix-etherial-lense/bandcamp24',
      '/release/tystix-etherial-lense/itunes',
      '/release/tystix-etherial-lense/beatport',
      '/release/tystix-etherial-lense/spotify',
      '/release/tystix-etherial-lense/junodownload',
      '/release/tystix-etherial-lense/youtube',
      '/release/tystix-etherial-lense/youtubemusic',
      '/release/tystix-etherial-lense/deezer',
      '/release/tystix-etherial-lense/tidal',
      '/release/tystix-etherial-lense/napster',
      '/release/tystix-etherial-lense/soundcloud',

      '/release/nuada-internal-quest',
      '/release/nuada-internal-quest/official',
      '/release/nuada-internal-quest/bandcamp',
      '/release/nuada-internal-quest/bandcamp24',
      '/release/nuada-internal-quest/itunes',
      '/release/nuada-internal-quest/beatport',
      '/release/nuada-internal-quest/spotify',
      '/release/nuada-internal-quest/junodownload',
      '/release/nuada-internal-quest/youtube',
      '/release/nuada-internal-quest/youtubemusic',
      '/release/nuada-internal-quest/deezer',
      '/release/nuada-internal-quest/tidal',
      '/release/nuada-internal-quest/napster',
      '/release/nuada-internal-quest/soundcloud',

      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/official',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/bandcamp',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/bandcamp24',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/itunes',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/beatport',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/spotify',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/junodownload',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/youtube',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/youtubemusic',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/deezer',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/tidal',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/napster',
      '/release/unusual-cosmic-process-e-mantra-sunrise-over-the-black-sea/soundcloud',

      '/release/noob-psybot-fiends-obscure-litany',
      '/release/noob-psybot-fiends-obscure-litany/official',
      '/release/noob-psybot-fiends-obscure-litany/bandcamp',
      '/release/noob-psybot-fiends-obscure-litany/bandcamp24',
      '/release/noob-psybot-fiends-obscure-litany/itunes',
      '/release/noob-psybot-fiends-obscure-litany/beatport',
      '/release/noob-psybot-fiends-obscure-litany/spotify',
      '/release/noob-psybot-fiends-obscure-litany/junodownload',
      '/release/noob-psybot-fiends-obscure-litany/youtube',
      '/release/noob-psybot-fiends-obscure-litany/youtubemusic',
      '/release/noob-psybot-fiends-obscure-litany/deezer',
      '/release/noob-psybot-fiends-obscure-litany/tidal',
      '/release/noob-psybot-fiends-obscure-litany/napster',
      '/release/noob-psybot-fiends-obscure-litany/soundcloud',

      '/release/va-futured-vol-5',
      '/release/va-futured-vol-5/official',
      '/release/va-futured-vol-5/bandcamp',
      '/release/va-futured-vol-5/bandcamp24',
      '/release/va-futured-vol-5/itunes',
      '/release/va-futured-vol-5/beatport',
      '/release/va-futured-vol-5/spotify',
      '/release/va-futured-vol-5/junodownload',
      '/release/va-futured-vol-5/youtube',
      '/release/va-futured-vol-5/youtubemusic',
      '/release/va-futured-vol-5/deezer',
      '/release/va-futured-vol-5/tidal',
      '/release/va-futured-vol-5/napster',
      '/release/va-futured-vol-5/soundcloud',

      '/release/frog-prog-sacred-journey',
      '/release/frog-prog-sacred-journey/official',
      '/release/frog-prog-sacred-journey/bandcamp',
      '/release/frog-prog-sacred-journey/bandcamp24',
      '/release/frog-prog-sacred-journey/itunes',
      '/release/frog-prog-sacred-journey/beatport',
      '/release/frog-prog-sacred-journey/spotify',
      '/release/frog-prog-sacred-journey/junodownload',
      '/release/frog-prog-sacred-journey/youtube',
      '/release/frog-prog-sacred-journey/youtubemusic',
      '/release/frog-prog-sacred-journey/deezer',
      '/release/frog-prog-sacred-journey/tidal',
      '/release/frog-prog-sacred-journey/napster',
      '/release/frog-prog-sacred-journey/soundcloud',

      '/release/irukanji-eleexr-i-have-something-to-show-you',
      '/release/irukanji-eleexr-i-have-something-to-show-you/official',
      '/release/irukanji-eleexr-i-have-something-to-show-you/bandcamp',
      '/release/irukanji-eleexr-i-have-something-to-show-you/bandcamp24',
      '/release/irukanji-eleexr-i-have-something-to-show-you/itunes',
      '/release/irukanji-eleexr-i-have-something-to-show-you/beatport',
      '/release/irukanji-eleexr-i-have-something-to-show-you/spotify',
      '/release/irukanji-eleexr-i-have-something-to-show-you/junodownload',
      '/release/irukanji-eleexr-i-have-something-to-show-you/youtube',
      '/release/irukanji-eleexr-i-have-something-to-show-you/youtubemusic',
      '/release/irukanji-eleexr-i-have-something-to-show-you/deezer',
      '/release/irukanji-eleexr-i-have-something-to-show-you/tidal',
      '/release/irukanji-eleexr-i-have-something-to-show-you/napster',
      '/release/irukanji-eleexr-i-have-something-to-show-you/soundcloud',

      '/release/from-vacuum-banglich',
      '/release/from-vacuum-banglich/official',
      '/release/from-vacuum-banglich/bandcamp',
      '/release/from-vacuum-banglich/bandcamp24',
      '/release/from-vacuum-banglich/itunes',
      '/release/from-vacuum-banglich/beatport',
      '/release/from-vacuum-banglich/spotify',
      '/release/from-vacuum-banglich/junodownload',
      '/release/from-vacuum-banglich/youtube',
      '/release/from-vacuum-banglich/youtubemusic',
      '/release/from-vacuum-banglich/deezer',
      '/release/from-vacuum-banglich/tidal',
      '/release/from-vacuum-banglich/napster',
      '/release/from-vacuum-banglich/soundcloud',

      '/release/declaration-of-unity-transpersonal',
      '/release/declaration-of-unity-transpersonal/official',
      '/release/declaration-of-unity-transpersonal/bandcamp',
      '/release/declaration-of-unity-transpersonal/bandcamp24',
      '/release/declaration-of-unity-transpersonal/itunes',
      '/release/declaration-of-unity-transpersonal/beatport',
      '/release/declaration-of-unity-transpersonal/spotify',
      '/release/declaration-of-unity-transpersonal/junodownload',
      '/release/declaration-of-unity-transpersonal/youtube',
      '/release/declaration-of-unity-transpersonal/youtubemusic',
      '/release/declaration-of-unity-transpersonal/deezer',
      '/release/declaration-of-unity-transpersonal/tidal',
      '/release/declaration-of-unity-transpersonal/napster',
      '/release/declaration-of-unity-transpersonal/soundcloud',

      '/release/psydewise-gain-of-funktion',
      '/release/psydewise-gain-of-funktion/official',
      '/release/psydewise-gain-of-funktion/bandcamp',
      '/release/psydewise-gain-of-funktion/bandcamp24',
      '/release/psydewise-gain-of-funktion/itunes',
      '/release/psydewise-gain-of-funktion/beatport',
      '/release/psydewise-gain-of-funktion/spotify',
      '/release/psydewise-gain-of-funktion/junodownload',
      '/release/psydewise-gain-of-funktion/youtube',
      '/release/psydewise-gain-of-funktion/youtubemusic',
      '/release/psydewise-gain-of-funktion/deezer',
      '/release/psydewise-gain-of-funktion/tidal',
      '/release/psydewise-gain-of-funktion/napster',
      '/release/psydewise-gain-of-funktion/soundcloud',

      '/release/tystix-romanesca',
      '/release/tystix-romanesca/official',
      '/release/tystix-romanesca/bandcamp',
      '/release/tystix-romanesca/bandcamp24',
      '/release/tystix-romanesca/itunes',
      '/release/tystix-romanesca/beatport',
      '/release/tystix-romanesca/spotify',
      '/release/tystix-romanesca/junodownload',
      '/release/tystix-romanesca/youtube',
      '/release/tystix-romanesca/youtubemusic',
      '/release/tystix-romanesca/deezer',
      '/release/tystix-romanesca/tidal',
      '/release/tystix-romanesca/napster',
      '/release/tystix-romanesca/soundcloud',

      '/release/eleexr-behind-dark-mirrors',
      '/release/eleexr-behind-dark-mirrors/official',
      '/release/eleexr-behind-dark-mirrors/bandcamp',
      '/release/eleexr-behind-dark-mirrors/bandcamp24',
      '/release/eleexr-behind-dark-mirrors/itunes',
      '/release/eleexr-behind-dark-mirrors/beatport',
      '/release/eleexr-behind-dark-mirrors/spotify',
      '/release/eleexr-behind-dark-mirrors/junodownload',
      '/release/eleexr-behind-dark-mirrors/youtube',
      '/release/eleexr-behind-dark-mirrors/youtubemusic',
      '/release/eleexr-behind-dark-mirrors/deezer',
      '/release/eleexr-behind-dark-mirrors/tidal',
      '/release/eleexr-behind-dark-mirrors/napster',
      '/release/eleexr-behind-dark-mirrors/soundcloud',

      '/release/jai-midi-bass',
      '/release/jai-midi-bass/official',
      '/release/jai-midi-bass/bandcamp',
      '/release/jai-midi-bass/bandcamp24',
      '/release/jai-midi-bass/itunes',
      '/release/jai-midi-bass/beatport',
      '/release/jai-midi-bass/spotify',
      '/release/jai-midi-bass/junodownload',
      '/release/jai-midi-bass/youtube',
      '/release/jai-midi-bass/youtubemusic',
      '/release/jai-midi-bass/deezer',
      '/release/jai-midi-bass/tidal',
      '/release/jai-midi-bass/napster',
      '/release/jai-midi-bass/soundcloud',

      '/release/paracozm-vorg-qube',
      '/release/paracozm-vorg-qube/official',
      '/release/paracozm-vorg-qube/bandcamp',
      '/release/paracozm-vorg-qube/bandcamp24',
      '/release/paracozm-vorg-qube/itunes',
      '/release/paracozm-vorg-qube/beatport',
      '/release/paracozm-vorg-qube/spotify',
      '/release/paracozm-vorg-qube/junodownload',
      '/release/paracozm-vorg-qube/youtube',
      '/release/paracozm-vorg-qube/youtubemusic',
      '/release/paracozm-vorg-qube/deezer',
      '/release/paracozm-vorg-qube/tidal',
      '/release/paracozm-vorg-qube/napster',
      '/release/paracozm-vorg-qube/soundcloud',

      '/release/va-futured-vol-6',
      '/release/va-futured-vol-6/official',
      '/release/va-futured-vol-6/bandcamp',
      '/release/va-futured-vol-6/bandcamp24',
      '/release/va-futured-vol-6/itunes',
      '/release/va-futured-vol-6/beatport',
      '/release/va-futured-vol-6/spotify',
      '/release/va-futured-vol-6/junodownload',
      '/release/va-futured-vol-6/youtube',
      '/release/va-futured-vol-6/youtubemusic',
      '/release/va-futured-vol-6/deezer',
      '/release/va-futured-vol-6/tidal',
      '/release/va-futured-vol-6/napster',
      '/release/va-futured-vol-6/soundcloud',

      '/release/space-organ-time-and-space',
      '/release/space-organ-time-and-space/official',
      '/release/space-organ-time-and-space/bandcamp',
      '/release/space-organ-time-and-space/bandcamp24',
      '/release/space-organ-time-and-space/itunes',
      '/release/space-organ-time-and-space/beatport',
      '/release/space-organ-time-and-space/spotify',
      '/release/space-organ-time-and-space/junodownload',
      '/release/space-organ-time-and-space/youtube',
      '/release/space-organ-time-and-space/youtubemusic',
      '/release/space-organ-time-and-space/deezer',
      '/release/space-organ-time-and-space/tidal',
      '/release/space-organ-time-and-space/napster',
      '/release/space-organ-time-and-space/soundcloud',

      '/release/urklang-psyral-lifeforms',
      '/release/urklang-psyral-lifeforms/official',
      '/release/urklang-psyral-lifeforms/bandcamp',
      '/release/urklang-psyral-lifeforms/bandcamp24',
      '/release/urklang-psyral-lifeforms/itunes',
      '/release/urklang-psyral-lifeforms/beatport',
      '/release/urklang-psyral-lifeforms/spotify',
      '/release/urklang-psyral-lifeforms/junodownload',
      '/release/urklang-psyral-lifeforms/youtube',
      '/release/urklang-psyral-lifeforms/youtubemusic',
      '/release/urklang-psyral-lifeforms/deezer',
      '/release/urklang-psyral-lifeforms/tidal',
      '/release/urklang-psyral-lifeforms/napster',
      '/release/urklang-psyral-lifeforms/soundcloud',
      
      // '/release/mushroomslice-astro-review',
      '/release/mushroomslice-astro-review/official',
      '/release/mushroomslice-astro-review/bandcamp',
      '/release/mushroomslice-astro-review/bandcamp24',
      '/release/mushroomslice-astro-review/itunes',
      '/release/mushroomslice-astro-review/beatport',
      '/release/mushroomslice-astro-review/spotify',
      '/release/mushroomslice-astro-review/junodownload',
      '/release/mushroomslice-astro-review/youtube',
      '/release/mushroomslice-astro-review/youtubemusic',
      '/release/mushroomslice-astro-review/deezer',
      '/release/mushroomslice-astro-review/tidal',
      '/release/mushroomslice-astro-review/napster',
      '/release/mushroomslice-astro-review/soundcloud',

      // '/release/spacecraft-metamorphosis',
      '/release/spacecraft-metamorphosis/official',
      '/release/spacecraft-metamorphosis/bandcamp',
      '/release/spacecraft-metamorphosis/bandcamp24',
      '/release/spacecraft-metamorphosis/itunes',
      '/release/spacecraft-metamorphosis/beatport',
      '/release/spacecraft-metamorphosis/spotify',
      '/release/spacecraft-metamorphosis/junodownload',
      '/release/spacecraft-metamorphosis/youtube',
      '/release/spacecraft-metamorphosis/youtubemusic',
      '/release/spacecraft-metamorphosis/deezer',
      '/release/spacecraft-metamorphosis/tidal',
      '/release/spacecraft-metamorphosis/napster',
      '/release/spacecraft-metamorphosis/soundcloud',

      // future releases

      '/release/vorg-cyber-soul',
      '/release/vorg-cyber-soul/official',
      '/release/vorg-cyber-soul/bandcamp',
      '/release/vorg-cyber-soul/bandcamp24',
      '/release/vorg-cyber-soul/itunes',
      '/release/vorg-cyber-soul/beatport',
      '/release/vorg-cyber-soul/spotify',
      '/release/vorg-cyber-soul/junodownload',
      '/release/vorg-cyber-soul/youtube',
      '/release/vorg-cyber-soul/youtubemusic',
      '/release/vorg-cyber-soul/deezer',
      '/release/vorg-cyber-soul/tidal',
      '/release/vorg-cyber-soul/napster',
      '/release/vorg-cyber-soul/soundcloud',

      '/release/va-gatekey-vol-3',
      '/release/va-gatekey-vol-3/official',
      '/release/va-gatekey-vol-3/bandcamp',
      '/release/va-gatekey-vol-3/bandcamp24',
      '/release/va-gatekey-vol-3/itunes',
      '/release/va-gatekey-vol-3/beatport',
      '/release/va-gatekey-vol-3/spotify',
      '/release/va-gatekey-vol-3/junodownload',
      '/release/va-gatekey-vol-3/youtube',
      '/release/va-gatekey-vol-3/youtubemusic',
      '/release/va-gatekey-vol-3/deezer',
      '/release/va-gatekey-vol-3/tidal',
      '/release/va-gatekey-vol-3/napster',
      '/release/va-gatekey-vol-3/soundcloud',

      // '/artist/irukanji',
      // '/artist/zymosis',
      // '/artist/kabi',
      // '/artist/psydewise',
      // '/artist/vorg',
      // '/artist/aesthesia',
      // '/artist/boketto',
      // '/artist/eleexr',
      // '/artist/exolt',
      // '/artist/gaz-mask',
      // '/artist/gojja',
      // '/artist/juelz',
      // '/artist/space-organ',
      // '/artist/altius',
      // '/artist/declaration-of-unity',
      // '/artist/hardcore-buddhist',
      // '/artist/kauyumari',
      // '/artist/mindex',
      // '/artist/overdream',
      // '/artist/paracozm',
      // '/artist/tystix',
      // '/artist/ufomatka',
      // '/artist/unusual-cosmic-process',
      // '/artist/psypheric',

      // '/artist/omnisound',
      // '/artist/tentura',
      // '/artist/erot',
      // '/artist/alexander-daf',
      // '/artist/already-maged',
      // '/artist/astropilot',
      // '/artist/calamus',
      // '/artist/encapsulate',
      // '/artist/chronos',
      // '/artist/cifroteca',
      // '/artist/crystal-vibe',
      // '/artist/dagas',
      // '/artist/daoine-sidhe',
      // '/artist/eguana',
      // '/artist/flooting-grooves',
      // '/artist/harax',
      // '/artist/heinali',
      // '/artist/hypnotriod',
      // '/artist/katya-chilly',
      // '/artist/magmadivers',
      // '/artist/neirula',
      // '/artist/psyfactor',
      // '/artist/roof-raiser',
      // '/artist/saikozaurus',
      // '/artist/senzar',
      // '/artist/shiva3',
      // '/artist/shivattva',
      // '/artist/shizolizer-gin',
      // '/artist/sky-technology',
      // '/artist/solcast',
      // '/artist/specialmind',
      // '/artist/spectrum-vision',
      // '/artist/sphingida',
      // '/artist/sygnals',
      // '/artist/tookytooky',
      // '/artist/unstable-elements',
      // '/artist/vonoom',

      // '/playlist/sentimony-official',
      '/playlist/sentimony-official/official',
      '/playlist/sentimony-official/applemusic',
      '/playlist/sentimony-official/spotify',
      '/playlist/sentimony-official/youtube',
      '/playlist/sentimony-official/youtubemusic',
      '/playlist/sentimony-official/deezer',
      '/playlist/sentimony-official/tidal',
      '/playlist/sentimony-official/napster',
      '/playlist/sentimony-official/soundcloud',

      // '/playlist/psychill-psybient',
      '/playlist/psychill-psybient/official',
      '/playlist/psychill-psybient/applemusic',
      '/playlist/psychill-psybient/spotify',
      '/playlist/psychill-psybient/youtube',
      '/playlist/psychill-psybient/youtubemusic',
      '/playlist/psychill-psybient/deezer',
      '/playlist/psychill-psybient/tidal',
      '/playlist/psychill-psybient/napster',
      '/playlist/psychill-psybient/soundcloud',

      // '/playlist/dark-prog-zenonesque',
      '/playlist/dark-prog-zenonesque/official',
      '/playlist/dark-prog-zenonesque/applemusic',
      '/playlist/dark-prog-zenonesque/spotify',
      '/playlist/dark-prog-zenonesque/youtube',
      '/playlist/dark-prog-zenonesque/youtubemusic',
      '/playlist/dark-prog-zenonesque/deezer',
      '/playlist/dark-prog-zenonesque/tidal',
      '/playlist/dark-prog-zenonesque/napster',
      '/playlist/dark-prog-zenonesque/soundcloud',

      // '/playlist/goa-trance',
      '/playlist/goa-trance/official',
      '/playlist/goa-trance/applemusic',
      '/playlist/goa-trance/spotify',
      '/playlist/goa-trance/youtube',
      '/playlist/goa-trance/youtubemusic',
      '/playlist/goa-trance/deezer',
      '/playlist/goa-trance/tidal',
      '/playlist/goa-trance/napster',
      '/playlist/goa-trance/soundcloud',

      // '/event/shift-space',
      // '/event/alt-space',
      // '/event/water-marks',
      // '/event/home-space',
      // '/event/five-years',
      //
      // '/friend/another-dimension',
      // '/friend/clocktail',
      // '/friend/moon-koradji',
      // '/friend/parvati',
      // '/friend/space-baby',
      // '/friend/treetrolla',
      // '/friend/zenon',
    ]
  }
}
