export default {
  icons: {
    bandcamp: 'https://content.sentimony.com/assets/img/svg-icons/bandcamp.svg?01',
    apple: 'https://content.sentimony.com/assets/img/svg-icons/apple-music.svg?01',
    apple_2: 'https://content.sentimony.com/assets/img/svg-icons/apple-music-2.svg?01',
    googleplay: 'https://content.sentimony.com/assets/img/svg-icons/google-play.svg?01',
    beatport: 'https://content.sentimony.com/assets/img/svg-icons/beatport.svg?01',
    spotify: 'https://content.sentimony.com/assets/img/svg-icons/spotify.svg?01',
    junodownload: 'https://content.sentimony.com/assets/img/svg-icons/junodownload.svg?01',
    youtube: 'https://content.sentimony.com/assets/img/svg-icons/youtube.svg?01',
    youtube_music: 'https://content.sentimony.com/assets/img/svg-icons/youtube-music.svg?01',
    youtube_music_2: 'https://content.sentimony.com/assets/img/svg-icons/youtube-music-2.svg?01',
    deezer: 'https://content.sentimony.com/assets/img/svg-icons/deezer.svg?01',
    tidal: 'https://content.sentimony.com/assets/img/svg-icons/tidal.svg?01',
    napster: 'https://content.sentimony.com/assets/img/svg-icons/napster.svg?01',
    soundcloud: 'https://content.sentimony.com/assets/img/svg-icons/soundcloud.svg?01',
    discogs: 'https://content.sentimony.com/assets/img/svg-icons/discogs.svg?01',
    facebook: 'https://content.sentimony.com/assets/img/svg-icons/facebook.svg?01',
    instagram: 'https://content.sentimony.com/assets/img/svg-icons/instagram.svg?01',
    mixcloud: 'https://content.sentimony.com/assets/img/svg-icons/mixcloud.svg?01',
    diggersfactory: 'https://content.sentimony.com/assets/img/svg-icons/discogs.svg?01',
  },
  routes: {
    bandcamp_24: 'bandcamp24',
    bandcamp_16: 'bandcamp',
    itunes: 'itunes',
    applemusic: 'applemusic',
    googleplay_market: 'googleplaymarket',
    googleplay_music: 'googleplay',
    googleplaymusic: 'googleplaymusic',
    beatport: 'beatport',
    spotify: 'spotify',
    junodownload: 'junodownload',
    youtube: 'youtube',
    youtube_music: 'youtubemusic',
    deezer: 'deezer',
    tidal: 'tidal',
    napster: 'napster',
    soundcloud: 'soundcloud',
    discogs: 'discogs',
    facebook: 'facebook',
    // instagram: 'instagram',
    // mixcloud: 'mixcloud',
    diggersfactory: 'diggersfactory',
  },
  titles: {
    bandcamp: 'Bandcamp',
    bandcamp_24: 'Bandcamp <small>24bit</small>',
    bandcamp_16: 'Bandcamp <small>16bit</small>',
    apple_music: 'Apple Music',
    itunes: 'iTunes',
    googleplay_music: 'GooglePlay Music',
    googleplay_market: 'GooglePlay Market',
    beatport: 'Beatport',
    spotify: 'Spotify',
    junodownload: 'JunoDownload',
    youtube: 'YouTube',
    youtube_full: 'YouTube <small>Full Release</small>',
    youtube_track: 'YouTube <small>Per Track</small>',
    youtube_music: 'YouTube Music',
    deezer: 'Deezer',
    tidal: 'Tidal',
    napster: 'Napster',
    soundcloud: 'SoundCloud',
    discogs: 'Discogs',
    facebook: 'Facebook',
    facebook_artist: 'Fb | Artist',
    facebook_personal: 'Fb | Person',
    instagram: 'Instagram',
    instagram_artist: 'Insta | Artist',
    instagram_personal: 'Insta | Person',
    mixcloud: 'Mixcloud',
    diggersfactory: 'Diggers Factory',
  },
  texts: {
    comingPhoto: 'Photo<br>coming<br>soon',
    comingArtwork: 'Artwork<br>in<br>progress',
  }
}
