export default {
  icons: {
    bandcamp: 'https://content.sentimony.com/assets/img/svg-icons/bandcamp.svg?01',
    apple: 'https://content.sentimony.com/assets/img/svg-icons/apple-music.svg?01',
    googleplay: 'https://content.sentimony.com/assets/img/svg-icons/google-play.svg?01',
    beatport: 'https://content.sentimony.com/assets/img/svg-icons/beatport.svg?01',
    spotify: 'https://content.sentimony.com/assets/img/svg-icons/spotify.svg?01',
    junodownload: 'https://content.sentimony.com/assets/img/svg-icons/junodownload.svg?01',
    youtube: 'https://content.sentimony.com/assets/img/svg-icons/youtube.svg?01',
    youtube_music: 'https://content.sentimony.com/assets/img/svg-icons/youtube-music.svg?01',
    deezer: 'https://content.sentimony.com/assets/img/svg-icons/deezer.svg?01',
    tidal: 'https://content.sentimony.com/assets/img/svg-icons/tidal.svg?01',
    napster: 'https://content.sentimony.com/assets/img/svg-icons/napster.svg?01',
  },
  routes: {
    bandcamp_24: 'bandcamp24',
    bandcamp_16: 'bandcamp',
    itunes: 'itunes',
    applemusic: 'applemusic',
    googleplay_market: 'googleplaymarket',
    googleplay_music: 'googleplay',
    googleplaymusic: 'googleplaymusic',
    beatport: 'beatport',
    spotify: 'spotify',
    junodownload: 'junodownload',
    youtube: 'youtube',
    youtube_music: 'youtubemusic',
    deezer: 'deezer',
    tidal: 'tidal',
    napster: 'napster',
  },
  titles: {
    bandcamp_24: 'Bandcamp 24bit',
    bandcamp_16: 'Bandcamp 16bit',
    apple_music: 'Apple Music',
    itunes: 'iTunes',
    googleplay_music: 'GooglePlay Music',
    googleplay_market: 'GooglePlay Market',
    beatport: 'Beatport',
    spotify: 'Spotify',
    junodownload: 'JunoDownload',
    youtube: 'YouTube',
    youtube_music: 'YouTube Music',
    deezer: 'Deezer',
    tidal: 'Tidal',
    napster: 'Napster',
  },
}
