export default {
  icons: {
    bandcamp: 'https://content.sentimony.com/assets/img/svg-icons/bandcamp.svg?01',
    apple: 'https://content.sentimony.com/assets/img/svg-icons/apple-music.svg?01',
    apple_2: 'https://content.sentimony.com/assets/img/svg-icons/apple-music-2.svg?01',
    googleplay: 'https://content.sentimony.com/assets/img/svg-icons/google-play.svg?01',
    beatport: 'https://content.sentimony.com/assets/img/svg-icons/beatport.svg?01',
    spotify: 'https://content.sentimony.com/assets/img/svg-icons/spotify.svg?01',
    junodownload: 'https://content.sentimony.com/assets/img/svg-icons/junodownload.svg?01',
    youtube: 'https://content.sentimony.com/assets/img/svg-icons/youtube.svg?01',
    youtube_music: 'https://content.sentimony.com/assets/img/svg-icons/youtube-music.svg?01',
    youtube_music_2: 'https://content.sentimony.com/assets/img/svg-icons/youtube-music-2.svg?01',
    deezer: 'https://content.sentimony.com/assets/img/svg-icons/deezer.svg?01',
    tidal: 'https://content.sentimony.com/assets/img/svg-icons/tidal.svg?01',
    napster: 'https://content.sentimony.com/assets/img/svg-icons/napster.svg?01',
    soundcloud: 'https://content.sentimony.com/assets/img/svg-icons/soundcloud.svg?01',
    discogs: 'https://content.sentimony.com/assets/img/svg-icons/discogs.svg?01',
    facebook: 'https://content.sentimony.com/assets/img/svg-icons/facebook.svg?01',
    instagram: 'https://content.sentimony.com/assets/img/svg-icons/instagram.svg?01',
    mixcloud: 'https://content.sentimony.com/assets/img/svg-icons/mixcloud.svg?01',
    qobuz: 'https://content.sentimony.com/assets/img/svg-icons/qobuz.svg?01',
    amazon_music: 'https://content.sentimony.com/assets/img/svg-icons/amazon-music.svg?01',
    diggersfactory: 'https://content.sentimony.com/assets/img/svg-icons/diggers-factory.svg?01',
  },
  routes: {
    bandcamp_24: 'bandcamp24',
    bandcamp_16: 'bandcamp',
    itunes: 'itunes',
    applemusic: 'applemusic',
    googleplay_market: 'googleplaymarket',
    googleplay_music: 'googleplay',
    googleplaymusic: 'googleplaymusic',
    beatport: 'beatport',
    spotify: 'spotify',
    junodownload: 'junodownload',
    youtube: 'youtube',
    youtube_playlist: 'youtubeplaylist',
    youtube_music: 'youtubemusic',
    deezer: 'deezer',
    tidal: 'tidal',
    napster: 'napster',
    soundcloud: 'soundcloud',
    discogs: 'discogs',
    facebook: 'facebook',
    // instagram: 'instagram',
    // mixcloud: 'mixcloud',
    qobuz: 'qobuz',
    amazon_music: 'amazonmusic',
    diggersfactory: 'diggersfactory',
  },
  titles: {
    bandcamp: 'Bandcamp',
    bandcamp_24: 'Bandcamp <small>(24bit)</small>',
    bandcamp_16: 'Bandcamp <small>(16bit)</small>',
    apple_music: 'Apple Music',
    itunes: 'iTunes',
    googleplay_music: 'GooglePlay Music',
    googleplay_market: 'GooglePlay Market',
    beatport: 'Beatport',
    spotify: 'Spotify',
    junodownload: 'JunoDownload',
    youtube: 'YouTube',
    youtube_full: 'YouTube <small>Full</small>',
    youtube_full_release: 'YouTube <small>Full Release</small>',
    youtube_per_track: 'YouTube <small>Per Track</small>',
    youtube_playlist: 'YouTube <small>Playlist</small>',
    youtube_indiv: 'YouTube <small>Individual Tracks</small>',
    youtube_music: 'YouTube Music',
    deezer: 'Deezer',
    tidal: 'Tidal',
    napster: 'Napster',
    soundcloud: 'SoundCloud',
    discogs: 'Discogs',
    facebook: 'Facebook',
    facebook_artist: 'Fb | Artist',
    facebook_personal: 'Fb | Person',
    instagram: 'Instagram',
    instagram_artist: 'Insta | Artist',
    instagram_personal: 'Insta | Person',
    mixcloud: 'Mixcloud',
    qobuz: 'Qobuz',
    amazon_music: 'Amazon Music',
    diggersfactory: 'Diggers Factory',
    website: 'Website',
  },
  texts: {
    comingPhoto: 'Photo<br>is<br>coming ⛄',
    comingCover: 'Cover<br>is<br>coming ⛄',
    comingMusic: 'Music<br>is<br>coming ⛄',
  },
  menu: [
    { visibleFooter: true, visibleHeader: false, visibleSidebar: true, title: 'Home', route: '/', match: p => p.startsWith('/index') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: 'News', route: '/news/', match: p => p.startsWith('/news') },
    { visibleFooter: true, visibleHeader: true, visibleSidebar: true, title: 'Releases', route: '/releases/', match: p => p.startsWith('/releases') || p.startsWith('/release/') },
    { visibleFooter: true, visibleHeader: true, visibleSidebar: true, title: 'Artists', route: '/artists/', match: p => p.startsWith('/artists') || p.startsWith('/artist/') },
    { visibleFooter: true, visibleHeader: true, visibleSidebar: true, title: 'Videos', route: '/videos/', match: p => p.startsWith('/videos') || p.startsWith('/video/') },
    { visibleFooter: true, visibleHeader: true, visibleSidebar: true, title: 'Playlists', route: '/playlists/', match: p => p.startsWith('/playlists') || p.startsWith('/playlist/') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: 'Events', route: '/events/', match: p => p.startsWith('/events') || p.startsWith('/event/') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: 'Friends', route: '/friends/', match: p => p.startsWith('/friends') || p.startsWith('/friend/') },
    { visibleFooter: true, visibleHeader: false, visibleSidebar: true, title: 'Contacts', route: '/contacts/', match: p => p.startsWith('/contacts') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: 'Tracks', route: '/tracks/', match: p => p.startsWith('/tracks') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: 'Sitemap', route: '/sitemap/', match: p => p.startsWith('/sitemap') },
    { visibleFooter: false, visibleHeader: false, visibleSidebar: false, title: '404', route: '/404/', match: p => p.startsWith('/404') },
  ]
}
